export * from "./patient/tabs/profile/patient-profile"
export * from "./patient/tabs/diagnosis/patient-diagnosis"
export * from "./patient/tabs/Medications/patient-medications"
export * from "./apoinment-details-screen/apoinment-details-screen"
export * from "./image-details-screen/image-details-screen"
export * from "./video-details-screen/video-details-screen"
