export * from "./welcome-screen/welcome-screen"
export * from "./demo-screen/demo-screen"
export * from "./patient/tabs/profile/patient-profile"
export * from "./patient/tabs/diagnosis/patient-diagnosis"
export * from "./patient/tabs/Medications/patient-medications"